### ISSUE TITLE
Undefined symbols

### ISSUE THREAD

**Issue by huyaoyu** [DimaRU/FastRTPSBridge#1]
I'm trying this [fork](https://github.com/janneskasper/FastRTPSSwift/tree/bugfix) and getting undefined symbols error.

System: 
macOS Sonoma 14.2.1
Xcode 15.0.1

Error message looks like the following:
```
Ld /Users/yaoyuh/Library/Developer/Xcode/DerivedData/SensorLoggerROS-bqosboshwqahtzaknpenxpfeztem/Build/Products/Debug-iphonesimulator/PackageFrameworks/FastRTPSBridge.framework/FastRTPSBridge normal (in target 'FastRTPSBridge' from project 'FastRTPSBridge')
...
...
ld: warning: ignoring duplicate libraries: '-lfastrtpsa'
ld: Undefined symbols:
  _BIO_ctrl, referenced from:
      asio::ssl::detail::engine::map_error_code(std::__1::error_code&) const in libfastrtpsa.a[166](TCPAcceptorSecure.o)
  _BIO_ctrl_pending, referenced from:
      asio::ssl::detail::engine::perform(int (asio::ssl::detail::engine::*)(void*, unsigned long), void*, unsigned long, std::__1::error_code&, unsigned long*) in libfastrtpsa.a[166](TCPAcceptorSecure.o)
      asio::ssl::detail::engine::perform(int (asio::ssl::detail::engine::*)(void*, unsigned long), void*, unsigned long, std::__1::error_code&, unsigned long*) in libfastrtpsa.a[166](TCPAcceptorSecure.o)
...
...
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The full error log is attached. 
[UndefinedSymbolsFastRTPSBridge.log](https://github.com/DimaRU/FastRTPSSwift/files/13796305/UndefinedSymbolsFastRTPSBridge.log)

Thank you!

**Comment by huyaoyu** [comment]
After googling around, I kinda think the problem might be that OpenSSL is not properly handled either by FastDDSPrebuild or (default) Xcode/Apple. I found a temporary solution that is adding [OpenSSL](https://github.com/krzyzanowskim/OpenSSL) as a dependency of the package target `FastRTPSWrapper`. This allows me to compile and link. But there are other weird problems like (not always) a very long compilation time and Xcode not being able to find the appropriate libraries to build for the iOS simulator. For those, I can open new GitHub issues.

**Comment by DimaRU** [comment]
I update FastDDSPrebuild and rebuilt the v2.6.6 release.
In the updated script TLS transport is explicitly disabled and OpenSSL is not used. Previously it was used by default.

Please make a new fork or clone because one commit was deleted.

I will also update FastRTPSSwift after the new year.
It will be used in developing an application for the Luxonis rae robot.
Happy New Year!

**Comment by huyaoyu** [comment]
Thank you so much for all the efforts! I will definitely try the update and report here. And can't wait to see the udpates in FastRTPSSwift and the deployment on Luxonis robots also.

Wish you a Happy New Year, too!

**Comment by huyaoyu** [comment]
Tested the `FastDDSPrebuild` Release 2.13.0 (current latest), it works with my [fork of FastTRPSSwift](https://github.com/huyaoyu/FastRTPSSwift/tree/fastdds2024). No more OpenSSL linking errors anymore. Thank you! Please consider closing this issue.

However, there is another issue while doing a release build against the simulator. I'll create a new issue.
