### ISSUE TITLE
Failed building FastRTPSBridge while doing release build for iOS simulator

### ISSUE THREAD

**Issue by huyaoyu** [DimaRU/FastRTPSBridge#2]
System: Sonoma 14.2.1
Xcode: 15.0.1

Using the FastDDSPrebuild Release 2.13.0, while doing a release build for the iOS simulator, there are many linking errors regarding fastrtps and fastdds. However other build scheme works, including
- Debug build for the iOS simulator
- Debug build for a real iPhone
- Release build for a real iPhone

I have set up a demo App to showcase the error https://github.com/huyaoyu/Test-DDS-iOS

After opening the above App project in Xcode, a build scheme needs to be created. Then change the scheme from Debug to Release and build for iOS simulator.  The detailed error message is attached here 
[Build Test-DDS-iOS-NoRoute2Host_2024-01-06T11-50-17.txt](https://github.com/DimaRU/FastRTPSSwift/files/13850518/Build.Test-DDS-iOS-NoRoute2Host_2024-01-06T11-50-17.txt)

Some samples from the error message look like the following:

```
Ld /Users/yaoyuh/Library/Developer/Xcode/DerivedData/Test-DDS-iOS-NoRoute2Host-ffvdgeisuuefdxcigbmsxslsgssq/Build/Intermediates.noindex/FastRTPSBridge.build/Release-iphonesimulator/FastRTPSBridge\ product.build/Objects-normal/x86_64/Binary/FastRTPSBridge normal x86_64 (in target 'FastRTPSBridge' from project 'FastRTPSBridge')
...
...
ld: warning: ignoring file '/Users/yaoyuh/Library/Developer/Xcode/DerivedData/Test-DDS-iOS-NoRoute2Host-ffvdgeisuuefdxcigbmsxslsgssq/Build/Products/Release-iphonesimulator/libfastrtpsa.a[258](virtual_memory.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/Users/yaoyuh/Library/Developer/Xcode/DerivedData/Test-DDS-iOS-NoRoute2Host-ffvdgeisuuefdxcigbmsxslsgssq/Build/Products/Release-iphonesimulator/libfastrtpsa.a[257](temporary_allocator.o)': found architecture 'arm64', required architecture 'x86_64'
...
...
ld: Undefined symbols:
...
...
eprosima::fastdds::dds::Log::SetVerbosity(eprosima::fastdds::dds::Log::Kind), referenced from:
      _setRTPSLoglevel in FastRTPSWrapper.o
...
eprosima::fastrtps::rtps::RTPSDomain::createRTPSReader(eprosima::fastrtps::rtps::RTPSParticipant*, eprosima::fastrtps::rtps::ReaderAttributes&, eprosima::fastrtps::rtps::ReaderHistory*, eprosima::fastrtps::rtps::ReaderListener*), referenced from:
...
```

It looks like it is related to some known issues with iOS simulators on Macs with Apple Silicon chips.  However, googling doesn't resolve the issue.

**Comment by DimaRU** [comment]
A lot of work has been done. Almost all FastDDSPrebuild binaries have been recompiled. Now all should work as expected.

**Comment by huyaoyu** [comment]
Awesome, I will test in the application I'm working on. Thank you!
