### ISSUE TITLE
Question: can I register multiple readers for the same topic?

### ISSUE THREAD

**Issue by huyaoyu** [DimaRU/FastRTPSBridge#3]
Can I register multiple readers for the same topic? Then I can have multiple types of completion functions working simultaneously. Based on my quick tests, it seems that one topic can only have one reader as shown by the following line https://github.com/DimaRU/FastRTPSSwift/blob/48f4776e9264d5d6beda21bd0bf05d5c0c34c228/Sources/FastRTPSWrapper/BridgedParticipant.cpp#L127

**Comment by DimaRU** [comment]
Based on the way DDS works, this is impossible and I don't really see why it's necessary.
But you can create another 'participant' and add the same topic to it.
