### ISSUE TITLE
Import FastRTPSSwift into swift playground

### ISSUE THREAD

**Issue by NDHANA94** [DimaRU/FastRTPSBridge#4]
Hi there!

Is there a way I can import fastRTPSSwift into a playground application? 
I tried to import it, but it gives an error while it imports fastDDSPrebuild. Playground cannot unzip it. 
If you can provide a solution, I’d really appreciate it 🙏🏼

![IMG_2252](https://github.com/DimaRU/FastRTPSSwift/assets/57376442/15c3b43f-a231-41ed-91c9-b9cfe1675da4)

**Comment by DimaRU** [comment]
Unfortunately, Swift Playgrounds cannot work with complex libraries. FastRTPSSwift contains Swift and C++ targets and a dependency on an external library. An SPM or Xcode project is a mandatory requirement.
